# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('param_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lsp', models.IntegerField()),
                ('plots', models.IntegerField()),
                ('pioneer', models.BooleanField()),
                ('neutral', models.BooleanField()),
                ('p_max', models.IntegerField()),
                ('p_num', models.IntegerField()),
                ('p_start', models.IntegerField()),
                ('np_max', models.IntegerField()),
                ('np_num', models.IntegerField()),
                ('np_start', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('sim_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('hill_num', models.CharField(max_length=3)),
                ('div_type', models.CharField(max_length=10)),
                ('s3_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='simulation',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divexplorer.User'),
        ),
    ]
