# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divexplorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contains',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contains',
            name='param_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divexplorer.Parameters'),
        ),
    ]
