# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divexplorer', '0002_parameters_sim_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Parameter',
        ),
    ]
