# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divexplorer', '0003_auto_20171019_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='sim_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
