# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divexplorer', '0003_remove_simulation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
