# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divexplorer', '0004_auto_20171019_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='lsp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='np_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='np_num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='np_start',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='p_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='p_num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='p_start',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='param_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='plots',
            field=models.PositiveIntegerField(),
        ),
    ]
