# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divexplorer', '0005_auto_20171020_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
